# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: podinfo2
  repo: https://stefanprodan.github.io/podinfo
  releaseName: podinfo2
  namespace: naikn
  version: '6.7.0'
