# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: mergestat
  repo: https://helm.mergestat.com/
  releaseName: mergestat
  namespace: admin
  version: 0.1.0
  valuesFile: values.yaml
